# Generated by Django 4.1.7 on 2023-03-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gross_weight_unit',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight_unit',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
