# Generated by Django 4.2 on 2023-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_gross_weight_unit_product_net_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='upload',
            field=models.ImageField(upload_to=models.CharField(max_length=128)),
        ),
    ]
