# Generated by Django 4.2 on 2023-04-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productimage_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageAdmin',
            fields=[
                ('productimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.productimage')),
            ],
            bases=('inventory.productimage',),
        ),
    ]
