# Generated by Django 4.2 on 2023-04-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productimageadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImageAdmin',
        ),
    ]
