# Generated by Django 4.2 on 2023-04-10 13:57

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_productimage_path_alter_productimage_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='upload',
            field=models.ImageField(upload_to=inventory.models.ProductImage._path),
        ),
    ]
