# Generated by Django 4.1.7 on 2023-03-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='core.nav')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
